
package com.project.webServices.jMoviesWebSoap.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Mon Apr 12 22:07:16 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getWorstReviews", namespace = "http://service.jMoviesWebSoap.webServices.project.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getWorstReviews", namespace = "http://service.jMoviesWebSoap.webServices.project.com/")

public class GetWorstReviews {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

